
# dput(pkgs)
pkgs <- 
  c("rlang", "cli", "glue", "lifecycle", "R6", "vctrs", "magrittr", 
    "Rcpp", "lattice", "withr", "jsonlite", "pkgconfig", "generics", 
    "cpp11", "Matrix", "digest", "utf8", "pillar", "tibble", "stringi", 
    "mime", "MASS", "RColorBrewer", "fastmap", "farver", "tidyselect", 
    "stringr", "viridisLite", "labeling", "curl", "scales", "base64enc", 
    "rappdirs", "purrr", "gtable", "dplyr", "S7", "isoband", "ggplot2", 
    "fs", "sys", "askpass", "cachem", "memoise", "yaml", "openssl", 
    "crayon", "htmltools", "tidyr", "codetools", "xfun", "evaluate", 
    "httr", "nlme", "highr", "jquerylib", "sass", "bslib", "fontawesome", 
    "knitr", "numDeriv", "survival", "backports", "abind", "tinytex", 
    "rmarkdown", "DBI", "bit", "BiocGenerics", "data.table", "bit64", 
    "RcppEigen", "prettyunits", "S4Vectors", "later", "matrixStats", 
    "zoo", "htmlwidgets", "IRanges", "otel", "png", "hms", "promises", 
    "KernSmooth", "XVector", "UCSC.utils", "class", "globals", "nnet", 
    "rstudioapi", "xml2", "GenomeInfoDb", "boot", "commonmark", "ps", 
    "tzdb", "BH", "Biobase", "mvtnorm", "processx", "progress", "rbibutils", 
    "Rdpack", "listenv", "nloptr", "parallelly", "broom", "future", 
    "minqa", "clipr", "httpuv", "plyr", "reformulas", "xtable", "Formula", 
    "blob", "lme4", "rprojroot", "gridExtra", "mgcv", "proxy", "MatrixGenerics", 
    "e1071", "forcats", "lazyeval", "vroom", "bitops", "callr", "cluster", 
    "future.apply", "readr", "S4Arrays", "SparseArray", "checkmate", 
    "colorspace", "desc", "formatR", "rpart", "sourcetools", "Biostrings", 
    "DelayedArray", "GenomicRanges", "RcppArmadillo", "XML", "cowplot", 
    "futile.options", "lambda.r", "plogr", "sandwich", "shiny", "snow", 
    "systemfonts", "futile.logger", "igraph", "insight", "timechange", 
    "BiocParallel", "MatrixModels", "RSQLite", "SparseM", "SummarizedExperiment", 
    "iterators", "lubridate", "modelr", "reshape2", "shape", "sp", 
    "Deriv", "classInt", "coda", "foreach", "microbenchmark", "quantreg", 
    "uuid", "wk", "doBy", "progressr", "s2", "units", "KEGGREST", 
    "carData", "crosstalk", "datawizard", "pbkrtest", "pkgbuild", 
    "rematch", "rjson", "sf", "sparsevctrs", "zip", "AnnotationDbi", 
    "SQUAREM", "hardhat", "haven", "httr2", "textshaping", "timeDate", 
    "xts", "R.methodsS3", "RcppTOML", "car", "cellranger", "dbplyr", 
    "deldir", "diagram", "ggrepel", "lava", "lmtest", "polyclip", 
    "quadprog", "R.oo", "here", "patchwork", "prodlim", "spatstat.utils", 
    "FNN", "R.utils", "RCurl", "Rhtslib", "bayestestR", "brio", "clock", 
    "filelock", "furrr", "gower", "gtools", "ipred", "jpeg", "litedown", 
    "readxl", "reticulate", "yulab.utils", "Rsamtools", "TH.data", 
    "ape", "diffobj", "distributional", "foreign", "markdown", "modeltools", 
    "pkgload", "ragg", "recipes", "terra", "warp", "whisker", "BiocFileCache", 
    "BiocIO", "GenomicAlignments", "RcppParallel", "RcppProgress", 
    "TTR", "config", "estimability", "fastmatch", "gargle", "geometries", 
    "gitcreds", "htmlTable", "ini", "libcoin", "locfit", "mnormt", 
    "multcomp", "parameters", "praise", "rapidjsonr", "rematch2", 
    "restfulr", "sitmo", "slider", "spatstat.data", "spatstat.univar", 
    "statmod", "tensorA", "tweenr", "viridis", "waldo", "AsioHeaders", 
    "BiocManager", "DEoptimR", "DiceDesign", "Hmisc", "RSpectra", 
    "Rhdf5lib", "SingleCellExperiment", "SnowballC", "V8", "corrplot", 
    "credentials", "dotCall64", "dqrng", "expm", "ggfun", "gridGraphics", 
    "irlba", "jose", "jsonify", "kernlab", "leaflet.providers", "lhs", 
    "limma", "mclust", "miniUI", "modelenv", "parsnip", "pbapply", 
    "pcaPP", "performance", "posterior", "pracma", "quantmod", "raster", 
    "reactR", "rsample", "rtracklayer", "selectr", "sfd", "sfheaders", 
    "spatstat.geom", "tensor", "testthat", "ucminf", "wavethresh", 
    "DT", "EbayesThresh", "GPfit", "GlobalOptions", "R.cache", "RcppAnnoy", 
    "annotate", "assertthat", "assorthead", "beachmat", "bigD", "brew", 
    "caTools", "dials", "fansi", "fontBitstreamVera", "fontLiberation", 
    "fracdiff", "geojsonsf", "gert", "ggforce", "ggplotify", "ggridges", 
    "ggsci", "ggsignif", "gh", "goftest", "juicyjuice", "leaflet", 
    "lmom", "maps", "mathjaxr", "mitools", "multcompView", "multicool", 
    "ordinal", "permute", "pixmap", "plotly", "polynom", "reactable", 
    "remotes", "repr", "rhdf5filters", "robustbase", "rootSolve", 
    "rstatix", "rvest", "scatterplot3d", "spam", "spatstat.random", 
    "spatstat.sparse", "stars", "tailor", "urca", "websocket", "workflows", 
    "yardstick", "AzureAuth", "BSgenome", "BiocNeighbors", "BiocSingular", 
    "BiocVersion", "Brobdingnag", "Exact", "GPArotation", "GenomicFeatures", 
    "KMsurv", "QuickJSR", "Rtsne", "ScaledMatrix", "StanHeaders", 
    "ade4", "adlift", "anytime", "aplot", "arm", "bdsmatrix", "beeswarm", 
    "ca", "cards", "chromote", "chron", "coin", "conflicted", "deSolve", 
    "doParallel", "downlit", "edgeR", "effectsize", "ellipse", "ellipsis", 
    "emmeans", "exactRankTests", "flashClust", "flexmix", "fontquiver", 
    "ggpubr", "gld", "googledrive", "gplots", "graph", "gridtext", 
    "gt", "ids", "inline", "interp", "janeaustenr", "jomo", "km.ci", 
    "ks", "labelled", "leafem", "leaps", "lobstr", "logger", "loo", 
    "lpSolve", "lwgeom", "magick", "metadat", "miscTools", "nortest", 
    "pan", "pander", "pbivnorm", "plotrix", "prismatic", "proto", 
    "rJava", "rentrez", "rex", "rhdf5", "rsvd", "scuttle", "servr", 
    "sessioninfo", "sjlabelled", "spatstat.explore", "stabledist", 
    "statnet.common", "stringdist", "stringmagic", "strucchange", 
    "survey", "svglite", "swagger", "sysfonts", "tfautograph", "tfruns", 
    "tidytree", "tokenizers", "treeio", "triebeard", "truncnorm", 
    "tseries", "tune", "uwot", "vegan", "vipor", "visNetwork", "xopen", 
    "zeallot", "ADGofTest", "AlgDesign", "AnnotationFilter", "AnnotationHub", 
    "AzureGraph", "BiocBaseUtils", "Cairo", "CompQuadForm", "DEoptim", 
    "DOSE", "DescTools", "DistributionUtils", "FactoMineR", "GOSemSim", 
    "GeneralizedHyperbolic", "GetoptLong", "IRdisplay", "ISOcodes", 
    "ModelMetrics", "NLP", "PKI", "PRROC", "PerformanceAnalytics", 
    "ProtGenerics", "RANN", "ROCR", "RProtoBufLib", "RcmdrMisc", 
    "RcppHNSW", "RcppML", "RcppRoll", "RobStatTM", "Rsolnp", "Rttf2pt1", 
    "SeuratObject", "SkewHyperbolic", "TMB", "TSP", "UpSetR", "VariantAnnotation", 
    "affyio", "ash", "aws.signature", "bayesplot", "bibliometrixData", 
    "bigmemory.sri", "binhf", "biomaRt", "biomformat", "biovizBase", 
    "bluster", "bookdown", "bridgesampling", "broom.mixed", "cardx", 
    "chk", "circlize", "clue", "clusterGeneration", "collapse", "cols4all", 
    "combinat", "contfrac", "corpcor", "cytolib", "dendextend", "dichromat", 
    "dimensionsR", "diptest", "dreamerr", "dtplyr", "effects", "elliptic", 
    "enrichplot", "ensembldb", "extrafontdb", "fastDummies", "fdrtool", 
    "fds", "fgsea", "fitdistrplus", "forecast", "gamlss.data", "gamlss.dist", 
    "gclus", "gdata", "gdtools", "genefilter", "getopt", "ggbeeswarm", 
    "ggeffects", "ggnewscale", "ggrastr", "ggstats", "ggtangle", 
    "ggtext", "ggtree", "git2r", "glasso", "glmnet", "gmp", "googlesheets4", 
    "graphlayouts", "gridBase", "gsl", "gson", "gss", "gsubfn", "h5mread", 
    "hdrcde", "httpcode", "hunspell", "ica", "infer", "intervals", 
    "inum", "latticeExtra", "lavaan", "leafgl", "leaflegend", "leafpop", 
    "leafsync", "leidenbase", "lgr", "linprog", "listviewer", "lmerTest", 
    "magic", "maptiles", "maxLik", "maxstat", "mcmc", "metafor", 
    "metapod", "mi", "mirai", "misc3d", "mitml", "mlbench", "mlr3measures", 
    "mlr3misc", "modeldata", "multtest", "nanonext", "network", "nleqslv", 
    "norm", "officer", "openalexR", "openxlsx", "optimParallel", 
    "pROC", "packrat", "padr", "paletteer", "palmerpenguins", "paradox", 
    "pbdZMQ", "phangorn", "pheatmap", "pingr", "pkgdown", "plotmo", 
    "polspline", "prabclus", "preprocessCore", "profmem", "profvis", 
    "pryr", "pspline", "psych", "pubmedR", "pyinit", "qap", "qpdf", 
    "qvalue", "rainbow", "rapportools", "rcmdcheck", "readstata13", 
    "registry", "relimp", "renv", "reprex", "rlist", "rngtools", 
    "roxygen2", "rrcov", "rscopus", "rstan", "rstantools", "rversions", 
    "satellite", "scattermore", "scatterpie", "sctransform", "segmented", 
    "sftime", "shinycssloaders", "shinyjs", "showtextdb", "sjmisc", 
    "sjstats", "slam", "slippymath", "snakecase", "snowflakeauth", 
    "sodium", "spData", "spacesXYZ", "spacetime", "sparklyr", "spatial", 
    "spatstat.linnet", "spatstat.model", "spd", "stopwords", "styler", 
    "survMisc", "tables", "tcltk2", "tensorflow", "tidygraph", "tidytext", 
    "timeSeries", "timetk", "tinytable", "tmaptools", "transformr", 
    "tsfeatures", "urlchecker", "urltools", "usethis", "visdat", 
    "webutils", "whoami", "workflowsets", "writexl", "xlsxjars", 
    "xmlparsedata", "zigg", "AER", "AzureRMR", "BiocStyle", "ComplexHeatmap", 
    "Cubist", "DESeq2", "DiagrammeR", "ExperimentHub", "GEOquery", 
    "GGally", "GSEABase", "Gviz", "HDF5Array", "IRkernel", "ISLR", 
    "JuliaCall", "Lahman", "MCMCpack", "MatchIt", "Metrics", "MultiAssayExperiment", 
    "R.rsp", "RJSONIO", "RMySQL", "RODBC", "RPostgreSQL", "RPostgres", 
    "RUnit", "Rcmdr", "Rfast", "Rgraphviz", "RhpcBLASctl", "Rmpfr", 
    "Seurat", "SpatialExperiment", "SuppDists", "VGAM", "admisc", 
    "afex", "affy", "agricolae", "archdata", "arrow", "arules", "aws.s3", 
    "bbmle", "bench", "betareg", "bibliometrix", "bigmemory", "bnlearn", 
    "botor", "brms", "broom.helpers", "caesar", "caret", "clusterProfiler", 
    "cmprsk", "colourpicker", "copula", "coro", "correlation", "countrycode", 
    "covr", "crul", "cubature", "cyclocomp", "data.tree", "dbscan", 
    "devtools", "doFuture", "doRNG", "doSNOW", "downloader", "drc", 
    "duckdb", "dygraphs", "earth", "evd", "extraDistr", "extrafont", 
    "fBasics", "factoextra", "fastICA", "fastcluster", "fda", "feather", 
    "ff", "fields", "fixest", "flextable", "float", "flowCore", "foghorn", 
    "formattable", "fpc", "gam", "gamlss", "gapminder", "gbm", "geepack", 
    "geometry", "geosphere", "getPass", "gganimate", "ggcorrplot", 
    "ggdendro", "ggdist", "ggfortify", "ggmap", "ggraph", "ggthemes", 
    "glmmTMB", "gmailr", "gmodels", "googleAuthR", "gstat", "gtExtras", 
    "gtsummary", "hexbin", "highcharter", "hypergeo", "implied", 
    "impute", "installr", "janitor", "jtools", "kableExtra", "keras", 
    "keyring", "latex2exp", "lintr", "mapproj", "mapview", "marginaleffects", 
    "meta", "mice", "minpack.lm", "mlflow", "mlr3", "mockery", "mockr", 
    "modelsummary", "moments", "msm", "munsell", "naniar", "nanoarrow", 
    "ncdf4", "nnls", "nycflights13", "odbc", "optimx", "optparse", 
    "pacman", "pak", "party", "partykit", "pastecs", "pdftools", 
    "phyloseq", "phytools", "piggyback", "pkgKitten", "plm", "plot3D", 
    "pls", "plumber", "prettydoc", "pscl", "pwr", "qgraph", "quanteda", 
    "quarto", "questionr", "randomForest", "ranger", "rcompanion", 
    "redoc", "reshape", "rgl", "rhub", "rio", "rjags", "rms", "rnaturalearth", 
    "rpart.plot", "rsconnect", "rsvg", "rugarch", "scater", "scran", 
    "sem", "seqinr", "seriation", "sfsmisc", "shinyBS", "shinyWidgets", 
    "shinydashboard", "shinytest2", "shinythemes", "showtext", "signal", 
    "sjPlot", "skimr", "slackr", "sn", "sna", "sparklyr.nested", 
    "spatstat", "spdep", "spelling", "sqldf", "stargazer", "summarytools", 
    "survminer", "sva", "tictoc", "tidymodels", "tidyquant", "tidyverse", 
    "tinytest", "tm", "tmap", "treemap", "tsibble", "umap", "vars", 
    "vcd", "vdiffr", "webshot", "webshot2", "wordcloud", "xgboost", 
    "xlsx")
  
# dput(build_pkgs)
build_pkgs <- 
  c("abind", "ade4", "adlift", "admisc", "AER", "afex", "agricolae", 
    "AlgDesign", "anytime", "ape", "aplot", "archdata", "arm", "arrow", 
    "arules", "AsioHeaders", "askpass", "assertthat", "aws.s3", "aws.signature", 
    "AzureAuth", "AzureGraph", "AzureRMR", "backports", "base64enc", 
    "bayesplot", "bayestestR", "bbmle", "bdsmatrix", "beeswarm", 
    "bench", "betareg", "BH", "bibliometrix", "bigD", "bigmemory", 
    "binhf", "BiocManager", "bit", "bit64", "bitops", "blob", "bnlearn", 
    "bookdown", "boot", "botor", "brew", "bridgesampling", "brio", 
    "brms", "Brobdingnag", "broom", "broom.helpers", "broom.mixed", 
    "bslib", "ca", "cachem", "caesar", "Cairo", "callr", "car", "carData", 
    "cards", "caret", "caTools", "cellranger", "checkmate", "chromote", 
    "chron", "circlize", "class", "classInt", "cli", "clipr", "clock", 
    "clue", "cluster", "cmprsk", "coda", "codetools", "coin", "collapse", 
    "colorspace", "colourpicker", "combinat", "commonmark", "CompQuadForm", 
    "config", "conflicted", "copula", "coro", "corpcor", "correlation", 
    "corrplot", "countrycode", "covr", "cowplot", "cpp11", "crayon", 
    "credentials", "crosstalk", "crul", "cubature", "Cubist", "curl", 
    "cyclocomp", "data.table", "data.tree", "datawizard", "DBI", 
    "dbplyr", "dbscan", "deldir", "dendextend", "DEoptimR", "Deriv", 
    "desc", "DescTools", "deSolve", "devtools", "diagram", "DiagrammeR", 
    "dials", "DiceDesign", "dichromat", "diffobj", "digest", "distributional", 
    "doBy", "doFuture", "doParallel", "doRNG", "doSNOW", "dotCall64", 
    "downlit", "downloader", "dplyr", "dqrng", "drc", "dreamerr", 
    "DT", "dtplyr", "duckdb", "dygraphs", "e1071", "earth", "EbayesThresh", 
    "effects", "effectsize", "ellipse", "ellipsis", "emmeans", "estimability", 
    "evaluate", "evd", "Exact", "exactRankTests", "expm", "extraDistr", 
    "extrafont", "extrafontdb", "factoextra", "FactoMineR", "fansi", 
    "farver", "fastcluster", "fastDummies", "fastICA", "fastmap", 
    "fastmatch", "fBasics", "fda", "fdrtool", "feather", "ff", "fields", 
    "filelock", "fitdistrplus", "fixest", "flashClust", "flexmix", 
    "flextable", "float", "FNN", "foghorn", "fontawesome", "fontBitstreamVera", 
    "fontLiberation", "fontquiver", "forcats", "foreach", "forecast", 
    "foreign", "formatR", "formattable", "Formula", "fpc", "fracdiff", 
    "fs", "furrr", "futile.logger", "futile.options", "future", "future.apply", 
    "gam", "gamlss", "gamlss.dist", "gapminder", "gargle", "gbm", 
    "gclus", "gdata", "gdtools", "geepack", "generics", "geojsonsf", 
    "geometries", "geometry", "geosphere", "gert", "GetoptLong", 
    "getPass", "GGally", "gganimate", "ggbeeswarm", "ggcorrplot", 
    "ggdendro", "ggdist", "ggeffects", "ggforce", "ggfortify", "ggfun", 
    "ggmap", "ggnewscale", "ggplot2", "ggplotify", "ggpubr", "ggraph", 
    "ggrepel", "ggridges", "ggsci", "ggsignif", "ggstats", "ggtext", 
    "ggthemes", "gh", "git2r", "gitcreds", "gld", "glmmTMB", "glmnet", 
    "GlobalOptions", "globals", "glue", "gmailr", "gmodels", "gmp", 
    "goftest", "googleAuthR", "googledrive", "googlesheets4", "gower", 
    "GPArotation", "GPfit", "gplots", "graphlayouts", "gridBase", 
    "gridExtra", "gridGraphics", "gridtext", "gsl", "gss", "gstat", 
    "gsubfn", "gt", "gtable", "gtExtras", "gtools", "gtsummary", 
    "hardhat", "haven", "here", "hexbin", "highcharter", "highr", 
    "Hmisc", "hms", "htmlTable", "htmltools", "htmlwidgets", "httpcode", 
    "httpuv", "httr", "httr2", "hunspell", "hypergeo", "ica", "ids", 
    "igraph", "implied", "infer", "ini", "inline", "insight", "installr", 
    "interp", "inum", "ipred", "IRdisplay", "IRkernel", "irlba", 
    "ISLR", "isoband", "iterators", "janeaustenr", "janitor", "jomo", 
    "jose", "jpeg", "jquerylib", "jsonify", "jsonlite", "jtools", 
    "juicyjuice", "JuliaCall", "kableExtra", "keras", "kernlab", 
    "KernSmooth", "keyring", "km.ci", "KMsurv", "knitr", "ks", "labeling", 
    "labelled", "Lahman", "lambda.r", "later", "latex2exp", "lattice", 
    "latticeExtra", "lava", "lavaan", "lazyeval", "leafem", "leaflet", 
    "leaflet.providers", "leaps", "leidenbase", "lgr", "lhs", "libcoin", 
    "lifecycle", "lintr", "listenv", "listviewer", "litedown", "lme4", 
    "lmerTest", "lmom", "lmtest", "lobstr", "locfit", "logger", "loo", 
    "lpSolve", "lubridate", "lwgeom", "magick", "magrittr", "mapproj", 
    "maps", "mapview", "marginaleffects", "markdown", "MASS", "MatchIt", 
    "mathjaxr", "Matrix", "MatrixModels", "matrixStats", "maxLik", 
    "maxstat", "mclust", "MCMCpack", "memoise", "meta", "metadat", 
    "metafor", "Metrics", "mgcv", "mi", "mice", "microbenchmark", 
    "mime", "miniUI", "minpack.lm", "minqa", "miscTools", "mitml", 
    "mitools", "mlbench", "mlflow", "mlr3", "mnormt", "mockery", 
    "mockr", "modeldata", "modelenv", "ModelMetrics", "modelr", "modelsummary", 
    "modeltools", "moments", "msm", "multcomp", "multcompView", "multicool", 
    "munsell", "mvtnorm", "naniar", "nanoarrow", "ncdf4", "network", 
    "nleqslv", "nlme", "nloptr", "NLP", "nnet", "nnls", "nortest", 
    "numDeriv", "nycflights13", "odbc", "officer", "openssl", "openxlsx", 
    "optimx", "optparse", "ordinal", "packrat", "pacman", "pak", 
    "paletteer", "palmerpenguins", "pan", "pander", "parallelly", 
    "parameters", "parsnip", "party", "partykit", "pastecs", "patchwork", 
    "pbapply", "pbivnorm", "pbkrtest", "pcaPP", "pdftools", "performance", 
    "PerformanceAnalytics", "permute", "phangorn", "pheatmap", "phytools", 
    "piggyback", "pillar", "pingr", "pixmap", "pkgbuild", "pkgconfig", 
    "pkgdown", "pkgKitten", "pkgload", "PKI", "plm", "plogr", "plot3D", 
    "plotly", "plotrix", "pls", "plumber", "plyr", "png", "polspline", 
    "polyclip", "polynom", "posterior", "pracma", "praise", "prettydoc", 
    "prettyunits", "prismatic", "pROC", "processx", "prodlim", "profmem", 
    "profvis", "progress", "progressr", "promises", "proto", "proxy", 
    "pryr", "ps", "pscl", "psych", "purrr", "pwr", "qap", "qgraph", 
    "qpdf", "quadprog", "quanteda", "quantmod", "quantreg", "quarto", 
    "questionr", "QuickJSR", "R.cache", "R.methodsS3", "R.oo", "R.rsp", 
    "R.utils", "R6", "ragg", "randomForest", "ranger", "RANN", "rapidjsonr", 
    "rappdirs", "raster", "rbibutils", "rcmdcheck", "Rcmdr", "RColorBrewer", 
    "rcompanion", "Rcpp", "RcppAnnoy", "RcppArmadillo", "RcppEigen", 
    "RcppHNSW", "RcppParallel", "RcppProgress", "RcppRoll", "RcppTOML", 
    "RCurl", "Rdpack", "reactable", "reactR", "readr", "readxl", 
    "recipes", "redoc", "reformulas", "registry", "rematch", "rematch2", 
    "remotes", "rentrez", "renv", "repr", "reprex", "reshape", "reshape2", 
    "restfulr", "reticulate", "rex", "Rfast", "rgl", "RhpcBLASctl", 
    "rhub", "rio", "rjags", "rJava", "rjson", "RJSONIO", "rlang", 
    "rlist", "rmarkdown", "Rmpfr", "rms", "RMySQL", "rnaturalearth", 
    "rngtools", "robustbase", "ROCR", "RODBC", "rootSolve", "roxygen2", 
    "rpart", "rpart.plot", "RPostgres", "RPostgreSQL", "rprojroot", 
    "rrcov", "rsample", "rsconnect", "Rsolnp", "RSpectra", "RSQLite", 
    "rstan", "rstantools", "rstatix", "rstudioapi", "rsvg", "Rtsne", 
    "Rttf2pt1", "rugarch", "RUnit", "rversions", "rvest", "s2", "S7", 
    "sandwich", "sass", "scales", "scattermore", "scatterpie", "scatterplot3d", 
    "sctransform", "segmented", "selectr", "sem", "seqinr", "seriation", 
    "servr", "sessioninfo", "Seurat", "SeuratObject", "sf", "sfd", 
    "sfheaders", "sfsmisc", "shape", "shiny", "shinyBS", "shinycssloaders", 
    "shinydashboard", "shinyjs", "shinytest2", "shinythemes", "shinyWidgets", 
    "showtext", "showtextdb", "signal", "sitmo", "sjlabelled", "sjmisc", 
    "sjPlot", "sjstats", "skimr", "slackr", "slam", "slider", "sn", 
    "sna", "snakecase", "snow", "SnowballC", "sodium", "sourcetools", 
    "sp", "spam", "sparklyr", "sparklyr.nested", "SparseM", "sparsevctrs", 
    "spatial", "spatstat", "spatstat.data", "spatstat.explore", "spatstat.geom", 
    "spatstat.random", "spatstat.sparse", "spatstat.univar", "spatstat.utils", 
    "spData", "spdep", "spelling", "sqldf", "SQUAREM", "stabledist", 
    "StanHeaders", "stargazer", "stars", "statmod", "statnet.common", 
    "stringdist", "stringi", "stringmagic", "stringr", "strucchange", 
    "styler", "summarytools", "SuppDists", "survey", "survival", 
    "survminer", "survMisc", "svglite", "sys", "sysfonts", "systemfonts", 
    "tensor", "tensorA", "tensorflow", "terra", "testthat", "textshaping", 
    "tfautograph", "tfruns", "TH.data", "tibble", "tictoc", "tidygraph", 
    "tidymodels", "tidyquant", "tidyr", "tidyselect", "tidytext", 
    "tidytree", "tidyverse", "timechange", "timeDate", "timeSeries", 
    "tinytest", "tinytex", "tm", "tmap", "tmaptools", "TMB", "tokenizers", 
    "treemap", "triebeard", "truncnorm", "tseries", "tsibble", "TSP", 
    "TTR", "tune", "tweenr", "tzdb", "ucminf", "umap", "units", "UpSetR", 
    "urca", "urlchecker", "urltools", "usethis", "utf8", "uuid", 
    "uwot", "V8", "vars", "vcd", "vctrs", "vdiffr", "vegan", "VGAM", 
    "vipor", "viridis", "viridisLite", "visdat", "visNetwork", "vroom", 
    "waldo", "warp", "wavethresh", "webshot", "webshot2", "websocket", 
    "webutils", "whisker", "whoami", "withr", "wk", "wordcloud", 
    "workflows", "workflowsets", "writexl", "xfun", "xgboost", "xlsx", 
    "xlsxjars", "XML", "xml2", "xmlparsedata", "xopen", "xtable", 
    "xts", "yaml", "yardstick", "yulab.utils", "zeallot", "zip", 
    "zoo", "affy", "AnnotationDbi", "AnnotationHub", "Biobase", "BiocFileCache", 
    "BiocGenerics", "BiocParallel", "BiocStyle", "biomaRt", "Biostrings", 
    "BSgenome", "clusterProfiler", "ComplexHeatmap", "DelayedArray", 
    "DESeq2", "edgeR", "ExperimentHub", "fgsea", "flowCore", "genefilter", 
    "GenomeInfoDb", "GenomicAlignments", "GenomicFeatures", "GenomicRanges", 
    "GEOquery", "ggtree", "graph", "GSEABase", "Gviz", "HDF5Array", 
    "impute", "IRanges", "limma", "MatrixGenerics", "MultiAssayExperiment", 
    "phyloseq", "preprocessCore", "qvalue", "Rgraphviz", "rhdf5", 
    "Rsamtools", "rtracklayer", "S4Vectors", "scater", "scran", "scuttle", 
    "SingleCellExperiment", "SpatialExperiment", "SummarizedExperiment", 
    "sva", "VariantAnnotation")