
# dput(pkgs)
pkgs <- 
  c("rlang", "cli", "glue", "lifecycle", "R6", "vctrs", "magrittr", 
    "Rcpp", "withr", "lattice", "pkgconfig", "digest", "jsonlite", 
    "utf8", "pillar", "tibble", "cpp11", "Matrix", "stringi", "generics", 
    "MASS", "RColorBrewer", "farver", "viridisLite", "fastmap", "labeling", 
    "tidyselect", "base64enc", "scales", "stringr", "mime", "rappdirs", 
    "gtable", "fs", "purrr", "S7", "isoband", "dplyr", "ggplot2", 
    "htmltools", "curl", "yaml", "cachem", "memoise", "xfun", "evaluate", 
    "tidyr", "highr", "jquerylib", "sass", "bslib", "fontawesome", 
    "knitr", "nlme", "sys", "askpass", "codetools", "numDeriv", "openssl", 
    "backports", "tinytex", "rmarkdown", "survival", "crayon", "RcppEigen", 
    "data.table", "later", "prettyunits", "htmlwidgets", "zoo", "httr", 
    "promises", "KernSmooth", "boot", "commonmark", "globals", "hms", 
    "ps", "rstudioapi", "DBI", "abind", "bit", "class", "processx", 
    "tzdb", "xml2", "nnet", "rbibutils", "Rdpack", "bit64", "mvtnorm", 
    "listenv", "minqa", "nloptr", "parallelly", "future", "httpuv", 
    "progress", "reformulas", "broom", "clipr", "lme4", "rprojroot", 
    "forcats", "plyr", "proxy", "xtable", "Formula", "callr", "e1071", 
    "gridExtra", "mgcv", "vroom", "desc", "future.apply", "png", 
    "readr", "sourcetools", "lazyeval", "rpart", "shiny", "checkmate", 
    "insight", "sandwich", "timechange", "colorspace", "lubridate", 
    "systemfonts", "MatrixModels", "RcppArmadillo", "SparseM", "cluster", 
    "coda", "cowplot", "modelr", "shape", "Deriv", "classInt", "microbenchmark", 
    "progressr", "quantreg", "wk", "bitops", "carData", "crosstalk", 
    "datawizard", "doBy", "igraph", "iterators", "matrixStats", "pkgbuild", 
    "rematch", "reshape2", "s2", "sp", "sparsevctrs", "units", "uuid", 
    "zip", "SQUAREM", "foreach", "hardhat", "haven", "pbkrtest", 
    "sf", "timeDate", "BH", "car", "cellranger", "diagram", "lava", 
    "textshaping", "xts", "RcppTOML", "blob", "deldir", "lmtest", 
    "polyclip", "prodlim", "quadprog", "spatstat.utils", "R.methodsS3", 
    "XML", "bayestestR", "brio", "clock", "furrr", "ggrepel", "gower", 
    "gtools", "here", "httr2", "ipred", "litedown", "readxl", "R.oo", 
    "TH.data", "diffobj", "distributional", "jpeg", "markdown", "patchwork", 
    "pkgload", "recipes", "reticulate", "terra", "warp", "whisker", 
    "FNN", "R.utils", "RcppParallel", "TTR", "config", "estimability", 
    "foreign", "gargle", "geometries", "gitcreds", "ini", "libcoin", 
    "multcomp", "parameters", "praise", "ragg", "rapidjsonr", "rematch2", 
    "slider", "spatstat.data", "spatstat.univar", "tensorA", "waldo", 
    "yulab.utils", "AsioHeaders", "DiceDesign", "SnowballC", "V8", 
    "corrplot", "credentials", "dotCall64", "htmlTable", "jose", 
    "jsonify", "leaflet.providers", "lhs", "miniUI", "mnormt", "modelenv", 
    "modeltools", "parsnip", "pbapply", "performance", "posterior", 
    "quantmod", "raster", "reactR", "rjson", "rsample", "sfd", "sfheaders", 
    "spatstat.geom", "tensor", "testthat", "tweenr", "ucminf", "viridis", 
    "wavethresh", "DEoptimR", "DT", "EbayesThresh", "GPfit", "Hmisc", 
    "R.cache", "RcppProgress", "assertthat", "bigD", "brew", "caTools", 
    "dbplyr", "dials", "expm", "fansi", "fontBitstreamVera", "fontLiberation", 
    "fracdiff", "geojsonsf", "gert", "ggridges", "ggsci", "ggsignif", 
    "gh", "goftest", "juicyjuice", "kernlab", "leaflet", "lmom", 
    "maps", "mathjaxr", "mclust", "mitools", "multcompView", "multicool", 
    "ordinal", "pcaPP", "plogr", "plotly", "polynom", "pracma", "reactable", 
    "remotes", "repr", "rootSolve", "rstatix", "scatterplot3d", "selectr", 
    "sitmo", "spam", "spatstat.random", "spatstat.sparse", "tailor", 
    "urca", "websocket", "workflows", "yardstick", "AzureAuth", "Brobdingnag", 
    "Exact", "GPArotation", "GlobalOptions", "KMsurv", "QuickJSR", 
    "RCurl", "RSpectra", "RcppAnnoy", "StanHeaders", "adlift", "anytime", 
    "ape", "arm", "bdsmatrix", "ca", "cards", "chromote", "chron", 
    "coin", "conflicted", "deSolve", "downlit", "dqrng", "effectsize", 
    "ellipse", "ellipsis", "emmeans", "exactRankTests", "fastmatch", 
    "flashClust", "fontquiver", "formatR", "ggforce", "ggfun", "ggpubr", 
    "gld", "googledrive", "gplots", "gridGraphics", "gridtext", "gt", 
    "ids", "inline", "irlba", "janeaustenr", "jomo", "km.ci", "ks", 
    "labelled", "leafem", "leaps", "lobstr", "logger", "loo", "lwgeom", 
    "metadat", "miscTools", "nortest", "pan", "pander", "pbivnorm", 
    "permute", "prismatic", "proto", "rJava", "rex", "robustbase", 
    "rvest", "servr", "sessioninfo", "sjlabelled", "spatstat.explore", 
    "stars", "statnet.common", "stringdist", "stringmagic", "strucchange", 
    "survey", "svglite", "swagger", "sysfonts", "tfautograph", "tfruns", 
    "tokenizers", "triebeard", "truncnorm", "tseries", "tune", "visNetwork", 
    "xopen", "zeallot", "AlgDesign", "AzureGraph", "CompQuadForm", 
    "DEoptim", "DescTools", "DistributionUtils", "FactoMineR", "GeneralizedHyperbolic", 
    "IRdisplay", "ISOcodes", "ModelMetrics", "NLP", "PKI", "PerformanceAnalytics", 
    "RANN", "ROCR", "RSQLite", "RcmdrMisc", "RcppHNSW", "RcppRoll", 
    "RobStatTM", "Rsolnp", "Rtsne", "Rttf2pt1", "SeuratObject", "SkewHyperbolic", 
    "TMB", "TSP", "UpSetR", "ash", "aws.signature", "bayesplot", 
    "beeswarm", "bibliometrixData", "binhf", "bridgesampling", "broom.mixed", 
    "cardx", "chk", "clusterGeneration", "collapse", "cols4all", 
    "combinat", "contfrac", "corpcor", "dendextend", "dimensionsR", 
    "doParallel", "dreamerr", "dtplyr", "effects", "elliptic", "extrafontdb", 
    "fastDummies", "fdrtool", "fds", "filelock", "fitdistrplus", 
    "forecast", "futile.options", "gclus", "gdata", "gdtools", "getopt", 
    "ggeffects", "ggplotify", "ggstats", "ggtext", "git2r", "glasso", 
    "glmnet", "gmp", "googlesheets4", "graphlayouts", "gridBase", 
    "gss", "gsubfn", "hdrcde", "httpcode", "hunspell", "ica", "infer", 
    "interp", "inum", "lambda.r", "lavaan", "leafgl", "leaflegend", 
    "leafpop", "leafsync", "leidenbase", "listviewer", "lmerTest", 
    "locfit", "lpSolve", "magick", "maptiles", "maxLik", "maxstat", 
    "mcmc", "metafor", "mi", "mitml", "modeldata", "network", "nleqslv", 
    "norm", "officer", "openalexR", "openxlsx", "optimParallel", 
    "pROC", "packrat", "padr", "paletteer", "pbdZMQ", "phangorn", 
    "pingr", "pixmap", "pkgdown", "plotrix", "polspline", "profmem", 
    "profvis", "pryr", "psych", "pubmedR", "pyinit", "qap", "qpdf", 
    "rainbow", "rapportools", "rcmdcheck", "readstata13", "registry", 
    "relimp", "rentrez", "renv", "reprex", "rlist", "rngtools", "roxygen2", 
    "rrcov", "rscopus", "rstan", "rstantools", "rversions", "satellite", 
    "scattermore", "sctransform", "shinycssloaders", "shinyjs", "showtextdb", 
    "sjmisc", "sjstats", "slam", "slippymath", "snakecase", "snowflakeauth", 
    "sodium", "spData", "spacesXYZ", "sparklyr", "spatial", "spatstat.linnet", 
    "spatstat.model", "spd", "stabledist", "stopwords", "styler", 
    "survMisc", "tables", "tcltk2", "tensorflow", "tidygraph", "tidytext", 
    "timeSeries", "timetk", "tinytable", "tmaptools", "transformr", 
    "tsfeatures", "urlchecker", "urltools", "usethis", "uwot", "vegan", 
    "vipor", "visdat", "webutils", "whoami", "workflowsets", "writexl", 
    "xlsxjars", "xmlparsedata", "zigg", "AER", "AzureRMR", "BiocManager", 
    "Cairo", "Cubist", "DiagrammeR", "GGally", "GetoptLong", "IRkernel", 
    "ISLR", "JuliaCall", "Lahman", "MCMCpack", "MatchIt", "Metrics", 
    "R.rsp", "RJSONIO", "RMySQL", "RODBC", "RPostgreSQL", "RPostgres", 
    "RUnit", "Rcmdr", "Rfast", "RhpcBLASctl", "Rmpfr", "Seurat", 
    "SuppDists", "VGAM", "ade4", "admisc", "afex", "agricolae", "aplot", 
    "archdata", "arrow", "arules", "aws.s3", "bbmle", "bench", "bibliometrix", 
    "bnlearn", "bookdown", "botor", "brms", "broom.helpers", "caesar", 
    "caret", "circlize", "clue", "cmprsk", "colourpicker", "coro", 
    "correlation", "countrycode", "covr", "crul", "cubature", "cyclocomp", 
    "dbscan", "devtools", "dichromat", "doFuture", "doRNG", "downloader", 
    "drc", "duckdb", "dygraphs", "evd", "extraDistr", "extrafont", 
    "fBasics", "factoextra", "fastICA", "fda", "feather", "ff", "fields", 
    "fixest", "flexmix", "flextable", "float", "foghorn", "formattable", 
    "futile.logger", "gam", "gapminder", "gbm", "geosphere", "getPass", 
    "gganimate", "ggbeeswarm", "ggcorrplot", "ggdist", "ggfortify", 
    "ggmap", "ggnewscale", "ggraph", "ggthemes", "glmmTMB", "gmailr", 
    "gmodels", "googleAuthR", "gsl", "gtExtras", "gtsummary", "hexbin", 
    "highcharter", "hypergeo", "implied", "installr", "janitor", 
    "jtools", "kableExtra", "keras", "keyring", "latticeExtra", "lgr", 
    "lintr", "mapproj", "mapview", "marginaleffects", "meta", "mice", 
    "minpack.lm", "mlbench", "mlflow", "mockery", "mockr", "modelsummary", 
    "moments", "munsell", "naniar", "nanoarrow", "ncdf4", "nycflights13", 
    "odbc", "optparse", "pacman", "pak", "palmerpenguins", "party", 
    "partykit", "pastecs", "pdftools", "pheatmap", "phytools", "piggyback", 
    "pkgKitten", "plm", "pls", "plumber", "prettydoc", "pscl", "pwr", 
    "qgraph", "quanteda", "quarto", "questionr", "randomForest", 
    "ranger", "rcompanion", "redoc", "reshape", "restfulr", "rgl", 
    "rhub", "rio", "rjags", "rms", "rnaturalearth", "rpart.plot", 
    "rsconnect", "rsvg", "rugarch", "scatterpie", "segmented", "sem", 
    "seriation", "shinyBS", "shinyWidgets", "shinydashboard", "shinytest2", 
    "shinythemes", "showtext", "sjPlot", "skimr", "slackr", "sna", 
    "snow", "sparklyr.nested", "spatstat", "spdep", "spelling", "sqldf", 
    "stargazer", "statmod", "summarytools", "survminer", "tidymodels", 
    "tidyquant", "tidytree", "tidyverse", "tinytest", "tm", "tmap", 
    "treemap", "tsibble", "vars", "vcd", "vdiffr", "webshot", "webshot2", 
    "wordcloud", "xgboost", "xlsx")
  
# dput(build_pkgs)
build_pkgs <- c("abind", "ade4", "adlift", "admisc", "AER", "afex", "agricolae", 
  "AlgDesign", "anytime", "ape", "aplot", "archdata", "arm", "arrow", 
  "arules", "AsioHeaders", "askpass", "assertthat", "aws.s3", "aws.signature", 
  "AzureAuth", "AzureGraph", "AzureRMR", "backports", "base64enc", 
  "bayesplot", "bayestestR", "bbmle", "bdsmatrix", "beeswarm", 
  "bench", "BH", "bibliometrix", "bigD", "binhf", "BiocManager", 
  "bit", "bit64", "bitops", "blob", "bnlearn", "bookdown", "boot", 
  "botor", "brew", "bridgesampling", "brio", "brms", "Brobdingnag", 
  "broom", "broom.helpers", "broom.mixed", "bslib", "ca", "cachem", 
  "caesar", "Cairo", "callr", "car", "carData", "cards", "caret", 
  "caTools", "cellranger", "checkmate", "chromote", "chron", "circlize", 
  "class", "classInt", "cli", "clipr", "clock", "clue", "cluster", 
  "cmprsk", "coda", "codetools", "coin", "collapse", "colorspace", 
  "colourpicker", "combinat", "commonmark", "CompQuadForm", "config", 
  "conflicted", "coro", "corpcor", "correlation", "corrplot", "countrycode", 
  "covr", "cowplot", "cpp11", "crayon", "credentials", "crosstalk", 
  "crul", "cubature", "Cubist", "curl", "cyclocomp", "data.table", 
  "datawizard", "DBI", "dbplyr", "dbscan", "deldir", "dendextend", 
  "DEoptimR", "Deriv", "desc", "DescTools", "deSolve", "devtools", 
  "diagram", "DiagrammeR", "dials", "DiceDesign", "dichromat", 
  "diffobj", "digest", "distributional", "doBy", "doFuture", "doParallel", 
  "doRNG", "dotCall64", "downlit", "downloader", "dplyr", "dqrng", 
  "drc", "dreamerr", "DT", "dtplyr", "duckdb", "dygraphs", "e1071", 
  "EbayesThresh", "effects", "effectsize", "ellipse", "ellipsis", 
  "emmeans", "estimability", "evaluate", "evd", "Exact", "exactRankTests", 
  "expm", "extraDistr", "extrafont", "extrafontdb", "factoextra", 
  "FactoMineR", "fansi", "farver", "fastDummies", "fastICA", "fastmap", 
  "fastmatch", "fBasics", "fda", "fdrtool", "feather", "ff", "fields", 
  "filelock", "fitdistrplus", "fixest", "flashClust", "flexmix", 
  "flextable", "float", "FNN", "foghorn", "fontawesome", "fontBitstreamVera", 
  "fontLiberation", "fontquiver", "forcats", "foreach", "forecast", 
  "foreign", "formatR", "formattable", "Formula", "fracdiff", "fs", 
  "furrr", "futile.logger", "futile.options", "future", "future.apply", 
  "gam", "gapminder", "gargle", "gbm", "gclus", "gdata", "gdtools", 
  "generics", "geojsonsf", "geometries", "geosphere", "gert", "GetoptLong", 
  "getPass", "GGally", "gganimate", "ggbeeswarm", "ggcorrplot", 
  "ggdist", "ggeffects", "ggforce", "ggfortify", "ggfun", "ggmap", 
  "ggnewscale", "ggplot2", "ggplotify", "ggpubr", "ggraph", "ggrepel", 
  "ggridges", "ggsci", "ggsignif", "ggstats", "ggtext", "ggthemes", 
  "gh", "git2r", "gitcreds", "gld", "glmmTMB", "glmnet", "GlobalOptions", 
  "globals", "glue", "gmailr", "gmodels", "gmp", "goftest", "googleAuthR", 
  "googledrive", "googlesheets4", "gower", "GPArotation", "GPfit", 
  "gplots", "graphlayouts", "gridBase", "gridExtra", "gridGraphics", 
  "gridtext", "gsl", "gss", "gsubfn", "gt", "gtable", "gtExtras", 
  "gtools", "gtsummary", "hardhat", "haven", "here", "hexbin", 
  "highcharter", "highr", "Hmisc", "hms", "htmlTable", "htmltools", 
  "htmlwidgets", "httpcode", "httpuv", "httr", "httr2", "hunspell", 
  "hypergeo", "ica", "ids", "igraph", "implied", "infer", "ini", 
  "inline", "insight", "installr", "interp", "inum", "ipred", "IRdisplay", 
  "IRkernel", "irlba", "ISLR", "isoband", "iterators", "janeaustenr", 
  "janitor", "jomo", "jose", "jpeg", "jquerylib", "jsonify", "jsonlite", 
  "jtools", "juicyjuice", "JuliaCall", "kableExtra", "keras", "kernlab", 
  "KernSmooth", "keyring", "km.ci", "KMsurv", "knitr", "ks", "labeling", 
  "labelled", "Lahman", "lambda.r", "later", "lattice", "latticeExtra", 
  "lava", "lavaan", "lazyeval", "leafem", "leaflet", "leaflet.providers", 
  "leaps", "leidenbase", "lgr", "lhs", "libcoin", "lifecycle", 
  "lintr", "listenv", "listviewer", "litedown", "lme4", "lmerTest", 
  "lmom", "lmtest", "lobstr", "locfit", "logger", "loo", "lpSolve", 
  "lubridate", "lwgeom", "magick", "magrittr", "mapproj", "maps", 
  "mapview", "marginaleffects", "markdown", "MASS", "MatchIt", 
  "mathjaxr", "Matrix", "MatrixModels", "matrixStats", "maxLik", 
  "maxstat", "mclust", "MCMCpack", "memoise", "meta", "metadat", 
  "metafor", "Metrics", "mgcv", "mi", "mice", "microbenchmark", 
  "mime", "miniUI", "minpack.lm", "minqa", "miscTools", "mitml", 
  "mitools", "mlbench", "mlflow", "mnormt", "mockery", "mockr", 
  "modeldata", "modelenv", "ModelMetrics", "modelr", "modelsummary", 
  "modeltools", "moments", "multcomp", "multcompView", "multicool", 
  "munsell", "mvtnorm", "naniar", "nanoarrow", "ncdf4", "network", 
  "nleqslv", "nlme", "nloptr", "NLP", "nnet", "nortest", "numDeriv", 
  "nycflights13", "odbc", "officer", "openssl", "openxlsx", "optparse", 
  "ordinal", "packrat", "pacman", "pak", "paletteer", "palmerpenguins", 
  "pan", "pander", "parallelly", "parameters", "parsnip", "party", 
  "partykit", "pastecs", "patchwork", "pbapply", "pbivnorm", "pbkrtest", 
  "pcaPP", "pdftools", "performance", "PerformanceAnalytics", "permute", 
  "pheatmap", "phytools", "piggyback", "pillar", "pingr", "pixmap", 
  "pkgbuild", "pkgconfig", "pkgdown", "pkgKitten", "pkgload", "PKI", 
  "plm", "plogr", "plotly", "plotrix", "pls", "plumber", "plyr", 
  "png", "polspline", "polyclip", "polynom", "posterior", "pracma", 
  "praise", "prettydoc", "prettyunits", "prismatic", "pROC", "processx", 
  "prodlim", "profmem", "profvis", "progress", "progressr", "promises", 
  "proto", "proxy", "pryr", "ps", "pscl", "psych", "purrr", "pwr", 
  "qap", "qgraph", "qpdf", "quadprog", "quanteda", "quantmod", 
  "quantreg", "quarto", "questionr", "QuickJSR", "R.cache", "R.methodsS3", 
  "R.oo", "R.rsp", "R.utils", "R6", "ragg", "randomForest", "ranger", 
  "RANN", "rapidjsonr", "rappdirs", "raster", "rbibutils", "rcmdcheck", 
  "Rcmdr", "RColorBrewer", "rcompanion", "Rcpp", "RcppAnnoy", "RcppArmadillo", 
  "RcppEigen", "RcppHNSW", "RcppParallel", "RcppProgress", "RcppRoll", 
  "RcppTOML", "RCurl", "Rdpack", "reactable", "reactR", "readr", 
  "readxl", "recipes", "redoc", "reformulas", "registry", "rematch", 
  "rematch2", "remotes", "rentrez", "renv", "repr", "reprex", "reshape", 
  "reshape2", "restfulr", "reticulate", "rex", "Rfast", "rgl", 
  "RhpcBLASctl", "rhub", "rio", "rjags", "rJava", "rjson", "RJSONIO", 
  "rlang", "rlist", "rmarkdown", "Rmpfr", "rms", "RMySQL", "rnaturalearth", 
  "rngtools", "robustbase", "ROCR", "RODBC", "rootSolve", "roxygen2", 
  "rpart", "rpart.plot", "RPostgres", "RPostgreSQL", "rprojroot", 
  "rrcov", "rsample", "rsconnect", "Rsolnp", "RSpectra", "RSQLite", 
  "rstan", "rstantools", "rstatix", "rstudioapi", "rsvg", "Rtsne", 
  "Rttf2pt1", "rugarch", "RUnit", "rversions", "rvest", "s2", "S7", 
  "sandwich", "sass", "scales", "scattermore", "scatterpie", "scatterplot3d", 
  "sctransform", "segmented", "selectr", "sem", "seriation", "servr", 
  "sessioninfo", "Seurat", "SeuratObject", "sf", "sfd", "sfheaders", 
  "shape", "shiny", "shinyBS", "shinycssloaders", "shinydashboard", 
  "shinyjs", "shinytest2", "shinythemes", "shinyWidgets", "showtext", 
  "showtextdb", "sitmo", "sjlabelled", "sjmisc", "sjPlot", "sjstats", 
  "skimr", "slackr", "slam", "slider", "sna", "snakecase", "snow", 
  "SnowballC", "sodium", "sourcetools", "sp", "spam", "sparklyr", 
  "sparklyr.nested", "SparseM", "sparsevctrs", "spatial", "spatstat", 
  "spatstat.data", "spatstat.explore", "spatstat.geom", "spatstat.random", 
  "spatstat.sparse", "spatstat.univar", "spatstat.utils", "spData", 
  "spdep", "spelling", "sqldf", "SQUAREM", "stabledist", "StanHeaders", 
  "stargazer", "stars", "statmod", "statnet.common", "stringdist", 
  "stringi", "stringmagic", "stringr", "strucchange", "styler", 
  "summarytools", "SuppDists", "survey", "survival", "survminer", 
  "survMisc", "svglite", "sys", "sysfonts", "systemfonts", "tensor", 
  "tensorA", "tensorflow", "terra", "testthat", "textshaping", 
  "tfautograph", "tfruns", "TH.data", "tibble", "tidygraph", "tidymodels", 
  "tidyquant", "tidyr", "tidyselect", "tidytext", "tidytree", "tidyverse", 
  "timechange", "timeDate", "timeSeries", "tinytest", "tinytex", 
  "tm", "tmap", "tmaptools", "TMB", "tokenizers", "treemap", "triebeard", 
  "truncnorm", "tseries", "tsibble", "TSP", "TTR", "tune", "tweenr", 
  "tzdb", "ucminf", "units", "UpSetR", "urca", "urlchecker", "urltools", 
  "usethis", "utf8", "uuid", "uwot", "V8", "vars", "vcd", "vctrs", 
  "vdiffr", "vegan", "VGAM", "vipor", "viridis", "viridisLite", 
  "visdat", "visNetwork", "vroom", "waldo", "warp", "wavethresh", 
  "webshot", "webshot2", "websocket", "webutils", "whisker", "whoami", 
  "withr", "wk", "wordcloud", "workflows", "workflowsets", "writexl", 
  "xfun", "xgboost", "xlsx", "xlsxjars", "XML", "xml2", "xmlparsedata", 
  "xopen", "xtable", "xts", "yaml", "yardstick", "yulab.utils", 
  "zeallot", "zip", "zoo")