# Tests for capture_covr_skip_report() — issue #150.
#
# The helper runs testthat on a package source and aggregates skip
# counts + top skip messages per test_that() block. It must return
# NULL (silently) for anything that isn't a testthat-shaped source
# tree and must never propagate an error from the wrapped test run.

.make_pkg_skeleton <- function(root, extra_test_files = list()) {
  # Minimal valid pkg skeleton: DESCRIPTION, NAMESPACE, tests/testthat/
  # with a canonical `tests/testthat.R` bootstrap. Extra test files are
  # written verbatim into tests/testthat/ from the named `extra_test_files`
  # list (name -> file contents).
  dir.create(file.path(root, "R"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(root, "tests", "testthat"),
             recursive = TRUE, showWarnings = FALSE)
  writeLines(
    c(
      "Package: skipdemo",
      "Type: Package",
      "Title: A Demo",
      "Version: 0.0.0.9000",
      "Description: For test-covr_skip_report tests.",
      "License: MIT + file LICENSE",
      "Encoding: UTF-8",
      "Suggests: testthat"
    ),
    file.path(root, "DESCRIPTION")
  )
  writeLines("# Generated by roxygen", file.path(root, "NAMESPACE"))
  writeLines(
    c(
      'library(testthat)',
      'test_check("skipdemo")'
    ),
    file.path(root, "tests", "testthat.R")
  )
  for (nm in names(extra_test_files)) {
    writeLines(extra_test_files[[nm]],
               file.path(root, "tests", "testthat", nm))
  }
  invisible(root)
}


test_that("capture_covr_skip_report() returns NULL when tests/testthat/ is absent", {
  root <- withr::local_tempdir()
  # No tests dir at all.
  dir.create(file.path(root, "R"), recursive = TRUE)
  writeLines("Package: nothing", file.path(root, "DESCRIPTION"))

  expect_null(capture_covr_skip_report(root))
})


test_that("capture_covr_skip_report() aggregates skip counts + top reasons per block", {
  root <- withr::local_tempdir()
  .make_pkg_skeleton(root, extra_test_files = list(
    "test-a.R" = c(
      'test_that("passes", { expect_true(TRUE) })',
      'test_that("also passes", { expect_equal(1 + 1, 2) })',
      'test_that("skip on cran", { skip_on_cran(); expect_true(TRUE) })',
      'test_that("skip with reason A", { skip("reason A"); expect_true(TRUE) })',
      'test_that("skip with reason A again", { skip("reason A"); expect_true(TRUE) })',
      'test_that("skip with reason B", { skip("reason B"); expect_true(TRUE) })'
    )
  ))

  # No NOT_CRAN in env -> skip_on_cran() fires. That's exactly the
  # gate this helper exists to measure.
  withr::local_envvar(NOT_CRAN = NA)

  rep <- capture_covr_skip_report(root)

  expect_type(rep, "list")
  expect_named(rep, c("totals", "top_reasons"))

  # 6 blocks total; 2 pass, 4 skip (skip_on_cran + reason A x2 +
  # reason B), 0 fail/error/warn.
  expect_identical(rep$totals$n_test,  6L)
  expect_identical(rep$totals$n_pass,  2L)
  expect_identical(rep$totals$n_skip,  4L)
  expect_identical(rep$totals$n_fail,  0L)
  expect_identical(rep$totals$n_error, 0L)

  # Top reasons sorted by frequency descending. "reason A" appears
  # twice; "reason B" and "On CRAN" (from skip_on_cran) once each.
  expect_s3_class(rep$top_reasons, "data.frame")
  expect_named(rep$top_reasons, c("reason", "n"))
  expect_identical(rep$top_reasons$reason[1], "reason A")
  expect_identical(rep$top_reasons$n[1], 2L)
  # "On CRAN" is skip_on_cran()'s default message in current testthat.
  expect_true("On CRAN" %in% rep$top_reasons$reason)
})


test_that("capture_covr_skip_report(env_vars) unblocks skip_on_cran when NOT_CRAN=true", {
  root <- withr::local_tempdir()
  .make_pkg_skeleton(root, extra_test_files = list(
    "test-a.R" = c(
      'test_that("skip_on_cran", { skip_on_cran(); expect_true(TRUE) })',
      'test_that("passes", { expect_true(TRUE) })'
    )
  ))

  # With NOT_CRAN=true injected via env_vars, skip_on_cran() must NOT
  # fire. This is the invariant Layer A (#146) is designed to
  # preserve — the standalone testthat run and the covr run must see
  # the same skip population.
  rep <- capture_covr_skip_report(
    root,
    env_vars = c(NOT_CRAN = "true", TESTTHAT = "true")
  )

  expect_identical(rep$totals$n_test, 2L)
  expect_identical(rep$totals$n_skip, 0L)
  expect_identical(rep$totals$n_pass, 2L)
  expect_identical(nrow(rep$top_reasons), 0L)
})


test_that("capture_covr_skip_report() returns NULL on test_dir() error, does not propagate", {
  root <- withr::local_tempdir()
  .make_pkg_skeleton(root, extra_test_files = list(
    # Deliberately malformed test file that will error during parse
    # / source, so testthat::test_dir() throws. The helper must
    # absorb it and return NULL, not derail val_pkg().
    "test-broken.R" = c(
      'test_that("broken", {',
      '  this_will_not_parse <-'
    )
  ))

  expect_silent(rep <- capture_covr_skip_report(root))
  expect_null(rep)
})


test_that("capture_covr_skip_report() rejects an unnamed env_vars input", {
  root <- withr::local_tempdir()
  .make_pkg_skeleton(root, extra_test_files = list(
    "test-a.R" = 'test_that("pass", { expect_true(TRUE) })'
  ))

  expect_error(
    capture_covr_skip_report(root, env_vars = c("true", "false")),
    "named character vector"
  )
})


test_that("capture_covr_skip_report() records '(no reason recorded)' when message is empty", {
  # Rare in real packages but real code exists that calls
  # `skip("")` or a custom skip that leaves the message unset.
  # The helper coalesces those into a single bucket so they don't
  # explode the top_reasons frequency table.
  root <- withr::local_tempdir()
  .make_pkg_skeleton(root, extra_test_files = list(
    "test-a.R" = c(
      'test_that("empty-message skip", { skip(""); expect_true(TRUE) })'
    )
  ))

  rep <- capture_covr_skip_report(root)

  expect_identical(rep$totals$n_skip, 1L)
  expect_true("(no reason recorded)" %in% rep$top_reasons$reason)
})

# ------------------------------------------------------------------
# pull_covr_skip_report_config() — gate resolver
# ------------------------------------------------------------------

test_that("pull_covr_skip_report_config() returns config defaults with no overrides", {
  withr::local_options(list(
    val.pipeline.capture_covr_skip_report = NULL,
    val.pipeline.covr_skip_report_threshold = NULL
  ))
  cfg <- pull_covr_skip_report_config()
  expect_identical(cfg$capture, TRUE)
  expect_identical(cfg$threshold, 65)
})

test_that("pull_covr_skip_report_config() honours capture-off R option override", {
  withr::local_options(list(
    val.pipeline.capture_covr_skip_report = FALSE
  ))
  cfg <- pull_covr_skip_report_config()
  expect_identical(cfg$capture, FALSE)
})

test_that("pull_covr_skip_report_config() honours threshold R option override", {
  withr::local_options(list(
    val.pipeline.covr_skip_report_threshold = 80
  ))
  cfg <- pull_covr_skip_report_config()
  expect_identical(cfg$threshold, 80)
})

test_that("pull_covr_skip_report_config() honours threshold=100 (capture-for-all path)", {
  # Sentinel value: any real coverage number is < 100, so gating on
  # `coverage < 100` captures every non-auto-accept pkg. This is the
  # documented way to opt into universal skip capture; NULL no
  # longer has special semantics.
  withr::local_options(list(
    val.pipeline.covr_skip_report_threshold = 100
  ))
  cfg <- pull_covr_skip_report_config()
  expect_identical(cfg$threshold, 100)
})

test_that("pull_covr_skip_report_config() rejects bad threshold", {
  withr::local_options(list(
    val.pipeline.covr_skip_report_threshold = 250
  ))
  expect_error(pull_covr_skip_report_config(),
               "threshold.*\\[0, 100\\]")
})

test_that("pull_covr_skip_report_config() rejects non-logical capture", {
  withr::local_options(list(
    val.pipeline.capture_covr_skip_report = "yes"
  ))
  expect_error(pull_covr_skip_report_config(),
               "capture.*must be TRUE or FALSE")
})

# ------------------------------------------------------------------
# covr_effective_coverage() — cheap upper-bound estimator
# ------------------------------------------------------------------

test_that("covr_effective_coverage() returns coverage unchanged when no skips", {
  expect_equal(covr_effective_coverage(50, 0), 50)
  expect_equal(covr_effective_coverage(90, 0), 90)
})

test_that("covr_effective_coverage() projects skipped tests at average rate", {
  # covr = 50%, 30% skipped -> effective = 50 / 0.7 = ~71.4
  expect_equal(covr_effective_coverage(50, 30), 50 / 0.7, tolerance = 1e-9)
  # covr = 40%, 50% skipped -> effective = 40 / 0.5 = 80
  expect_equal(covr_effective_coverage(40, 50), 80, tolerance = 1e-9)
})

test_that("covr_effective_coverage() caps at 100", {
  # covr = 80%, 90% skipped -> 80 / 0.1 = 800, capped at 100
  expect_equal(covr_effective_coverage(80, 90), 100)
})

test_that("covr_effective_coverage() returns NA on divide-by-zero and bad input", {
  expect_true(is.na(covr_effective_coverage(50, 100)))
  expect_true(is.na(covr_effective_coverage(NA_real_, 30)))
  expect_true(is.na(covr_effective_coverage(50, NA_real_)))
  expect_true(is.na(covr_effective_coverage(Inf, 30)))
  expect_true(is.na(covr_effective_coverage(numeric(0), 30)))
})
