default:
  decisions_lst: [Low, Medium, High]
  opt_repos: 
    CRAN: https://cran.r-project.org
    BioC: https://bioconductor.org/packages/3.17/bioc
remote_reduce:
  inherits: default
  downloads_1yr:
    cond:
      # High: ~ 
      High: ~ is.na(.x) | .x < 120000
      Medium: ~ dplyr::between(.x, 120000, 240000)
      Low: ~ .x > 240000
    type: primary
    accept_cats: Low
    min_value: 40000
  reverse_dependencies:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x < 2
      Medium: ~ dplyr::between(.x, 2, 7)
      Low: ~ .x > 7
    type: exception
    accept_cats: [Low, Medium]
  dependencies:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x > 8
      Medium: ~ dplyr::between(.x, 4, 8)
      Low: ~ .x < 4
    type: exception
    accept_cats: [Low, Medium]
  news_current:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x != 1
      Low: ~ .x == 1
    type: exception
    accept_cats: Low
  has_vignettes:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x < 1
      Medium: ~ .x == 1
      Low: ~ .x > 1
    type: exception
    accept_cats: Low
  has_source_control:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x == 0
      Low: ~ .x > 0
    type: exception
    accept_cats: Low
  has_website:
    cond:
      # High: ~ is.na(.x)
      High: ~ .x == 0
      Low: ~ .x > 0
    type: exception
    accept_cats: Low


decide_remote:
  inherits: default
  covr_coverage:
    cond:
      High: ~ is.na(.x) | .x < 30
      Medium: ~ dplyr::between(.x, 30, 60)
      Low: ~ .x > 50
    type: primary
    accept_cats: Low




# Okay! Need to create the 
# covr_coverage
    # filecoverage <- assessed$covr_coverage$filecoverage
  # has_news
  # bugs_status
  # remote_checks
  # r_cmd_check (errors & warnings)
  # exported_namespace
  # export_help
  # has_maintainer
  # size_codebase
  # has_bug_reports_url
  # has_examples
  # license
  